### ISSUE TITLE
Error:  Permission denied

### ISSUE THREAD

**Issue by Leo-Lee15** [jcrodriguez1989/shinyParallel#1]
Hi， 

Thanks for this awesome package!

When I follow your instructions in the README.md, I met the following error in the log file:
```
su: ignore --preserve-environment, it's mutually exclusive to --login.
-bash: line 0: cd: /srv/shiny-server/shinyParallel_appLinks/myShinyApp/myShinyApp_1: Permission denied
```

I think this issue is related to the permission. However, I've already run R as root.
```shell
sudo -u root R
```
And the R code is 
```r
library('shinyParallel');
shinyParallel::installShinyParallel('~/myShinyApp', max.sessions=20, users.per.session=5);
```
Could you point out what mistake I've made? 
Thanks!
-----
```r
> sessioninfo::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       CentOS Linux 7 (Core)       
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.utf8                  
 ctype    en_US.utf8                  
 tz       Asia/Shanghai               
 date     2019-06-22                  

─ Packages ───────────────────────────────────────────────────────────────────
 package       * version date       lib
 assertthat      0.2.0   2017-04-11 [1]
 callr           3.1.1   2018-12-21 [1]
 cli             1.0.1   2018-09-25 [1]
 crayon          1.3.4   2017-09-16 [1]
 digest          0.6.18  2018-10-10 [1]
 htmltools       0.3.6   2017-04-28 [1]
 httpuv          1.4.5.1 2018-12-18 [1]
 later           0.7.5   2018-09-18 [1]
 magrittr        1.5     2014-11-22 [1]
 mime            0.6     2018-10-05 [1]
 processx        3.2.1   2018-12-05 [1]
 promises        1.0.1   2018-04-13 [1]
 ps              1.3.0   2018-12-21 [1]
 R.methodsS3     1.7.1   2016-02-16 [1]
 R.oo            1.22.0  2018-04-22 [1]
 R.utils         2.9.0   2019-06-13 [1]
 R6              2.3.0   2018-10-04 [1]
 Rcpp            1.0.0   2018-11-07 [1]
 sessioninfo     1.1.1   2018-11-05 [1]
 shiny           1.2.0   2018-11-02 [1]
 shinyParallel   0.1.001 2019-06-21 [1]
 withr           2.1.2   2018-03-15 [1]
 xtable          1.8-3   2018-08-29 [1]
 source                                        
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.1)                                
 Github (jcrodriguez1989/shinyParallel@0d4e322)
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.0)                                

[1] /usr/lib64/R/library
[2] /usr/share/R/library

```

**Comment by jcrodriguez1989** [comment]
Hi @Leo-Lee15 , 
thanks for reporting this issue!

Could you try reinstalling `shinyParallel`:

```r
devtools::install_github("jcrodriguez1989/shinyParallel")
```

And then try to reproduce like this:

```r
sudo R
library('shinyParallel');
shinyParallel::installShinyParallel('~/myShinyApp', max.sessions=20, users.per.session=5);
```

thanks!

**Comment by jcrodriguez1989** [comment]
Well, I don't think this issue got fixed with my last commit.
The README is not correct ha.
You could install the shiny app by giving the full path:
```r
shinyParallel::installShinyParallel('/home/MY_USER_NAME/myShinyApp', max.sessions=20, users.per.session=5)
```

**Comment by Leo-Lee15** [comment]
Hi @jcrodriguez1989 

Thanks for your quick response!

However, I still cannot solve the permission issue based on your full-path solution. I find that if you create an app in the `home` directory of a particular user, it will always get the `permission denied` result.
But when I just create the shiny app in the `/srv/shiny-server/shiny-apps` directory, it seems that the permission problem is solved. However, new problem arises. I can't connect to the server when I just open the url of `myShiny` app. See my following screenshot:
![image](https://user-images.githubusercontent.com/18102092/59964050-f6e85900-952d-11e9-82c4-96449aa760ab.png). 

When I try to print the logs of shiny, I just see the following words:
```
cat: myShinyApp_10-shiny-20190622-204303-33082.log: No such file or directory
```

It is clear that all the necessary files are in the target directory.
```
[root@**_centos shiny-server]# ll
total 72
drwxr-xr-x 2 root root  4096 Jun 21 23:44 app_parallel
drwxr-xr-x 4 root root  4096 Dec 23 16:56 css
-rw-r--r-- 1 root root   335 Dec 23 16:56 favicon.png
drwxr-xr-x 4 root root  4096 Dec 23 16:56 fonts
drwxr-xr-x 2 root root  4096 Dec 23 16:56 images
-rw-r--r-- 1 root root  8833 Dec 23 18:16 index.html
drwxr-xr-x 2 root root  4096 Dec 23 16:56 js
drwxr-xr-x 2 root root  4096 Jun 22 20:31 myShinyApp
drwxr-xr-x 2 root root  4096 Dec 23 17:00 personal_site
lrwxrwxrwx 1 root root    37 Jul  7  2018 sample-apps -> /opt/shiny-server/samples/sample-apps
drwxr-xr-x 4 root root  4096 Jun 22 20:30 shiny-apps
drwxr-xr-x 3 root root  4096 Jun 22 20:30 shinyParallel_appLinks
-rw-r--r-- 1 root root 19669 Dec 23 16:56 styles.html
```

**Comment by jcrodriguez1989** [comment]
You should not copy manually the files as it won't work, shinyParallel is creating some extra files.
I have just reproduced the README from zero and it is working on my computer (Ubuntu).
Let's try to figure out what is going on in yours, please copy all the outputs you are getting.
Note that I have updated some README chunks, so follow this post.

First, delete shinyParallel logs:
```
sudo rm /var/log/shiny-server/myShinyApp*
```
Now, delete the created apps:
```
sudo rm -fr /srv/shiny-server/myShinyApp*
sudo rm -fr /srv/shiny-server/shinyParallel_appLinks
```
Start over with the README:
```
cd ~;
mkdir myShinyApp;
echo "
    library('shiny');
    
    # Create a Shiny app object
    app <- shinyApp(
      ui = fluidPage(
        column(3, wellPanel(
          numericInput('n', label='Is it prime?', value=7, min=1),
          actionButton('check', 'Check!')
        )
      )),
      server = function(input, output) {
        # Check if n is prime.
        # Not R optimized.
        # No Fermat, Miller-Rabin, Solovay-Strassen, Frobenius, etc tests.
        # Check if n is divisable up to n-1 !!
        isPrime <- function(n) {
          res <- TRUE;
          i <- 2;
          while (i < n) {
            res <- res && n %% i != 0;
            i <- i+1;
          }
          return(res);
        }
        observeEvent(input\$check, {
          showModal(modalDialog(
            ifelse(isPrime(isolate(input\$n)),
                'Yes it is!', 'Nope, not a prime.'),
            footer=NULL,
            easyClose=TRUE
          ))
        })
      }
    )
" > myShinyApp/app.R;
```
Start a sudo R session
```
sudo R
```
And from R, with shinyParallel, install the app in the server
```r
library("shinyParallel")
# And install it
shinyParallel::installShinyParallel("./myShinyApp",
  max.sessions = 20,
  users.per.session = 5
)
```

Now, lets see what you have installed:
```
sudo ls -la /srv/shiny-server/
```
    ## total 16
    ## drwxr-xr-x 4 root root 4096 jun 22 13:57 .
    ## drwxr-xr-x 3 root root 4096 jun 21 14:39 ..
    ## drwxr-xr-x 2 root root 4096 jun 22 13:57 myShinyApp
    ## drwxr-xr-x 3 root root 4096 jun 22 13:57 shinyParallel_appLinks

Open the app in a browser [http://localhost:3838/myShinyApp/](http://localhost:3838/myShinyApp/)
And check if we have any logs:
```
sudo cat /var/log/shiny-server/myShinyApp*
```

thanks for your feedback!

**Comment by Leo-Lee15** [comment]
Thanks very much for your patience!
Here is whole input and output based on your above instructions:
```shell
[root@VM_0_8_centos ~]# rm -rf myShinyApp/
[root@VM_0_8_centos ~]# ll
total 720108
-rw-r--r-- 1 root root    302015 Oct 20  2017 3e9c099671820a30bf5d56e4a3814f64c831.pdf
-rw-r--r-- 1 root root  11237798 Sep  5  2018 apache-tomcat-8.5.34-windows-x64.zip
-rw-r--r-- 1 root root    188839 Jun 22 23:37 icudt61l.zip
-rw-r--r-- 1 root root      5444 Apr  7  2018 index.html
-rw-r--r-- 1 root root    238570 Dec 25 22:57 index.html.1
-rw-r--r-- 1 root root    149811 Dec 25 22:57 index.html?sku=Community
-rw-r--r-- 1 root root     26926 Oct  1  2018 jupyter_notebook_config.py
-rw-r--r-- 1 root root 170268287 Oct 21  2016 kie-server-distribution-6.5.0.Final.zip
-rw-r--r-- 1 root root    659802 Dec  5  2018 Lect1Station.pdf
-rw-r--r-- 1 root root  20105266 Jun 10  2018 LinuxProbe.pdf
-rw-r--r-- 1 root root   2928388 Oct 19  2018 master
-rw-r--r-- 1 root root      1022 Oct 20  2018 my.log
-rw-r--r-- 1 root root      6140 Nov 12  2015 mysql-community-release-el7-5.noarch.rpm
-rw------- 1 root root       462 Oct  1  2018 nohup.out
-rw-r--r-- 1 root root  83735016 Apr 26 19:16 R-3.6.0-win.exe
-rw-r--r-- 1 root root        59 Nov 29  2018 readme.txt
-rw-r--r-- 1 root root  89991619 Oct 30  2018 RStudio-1.1.463.exe
-rw-r--r-- 1 root root  18939524 Nov 26  2018 RStudio-1.2.1139.exe
-rw-r--r-- 1 root root     34436 Mar 30 19:04 RStudio-1.2.1335.exe
-rw-r--r-- 1 root root 133012196 Apr 13 20:42 RStudio-1.2.1335.exe.zip
-rw-r--r-- 1 root root  45678124 May 17  2018 rstudio-server-rhel-1.1.453-x86_64.rpm
-rw-r--r-- 1 root root  49141116 Apr  9 02:39 rstudio-server-rhel-1.2.1335-x86_64.rpm
drwxr-xr-x 3 root root      4096 Apr 11 22:49 sakila
-rw-r--r-- 1 root root       114 Apr 11 22:46 sakila-db.tar.gz
-rw-r--r-- 1 root root  48462832 Apr  7  2018 shiny-server-1.5.7.907-rh6-x86_64.rpm
drwxr-xr-x 2 root root      4096 Oct  1  2018 softwares
-rw-r--r-- 1 root root        52 Nov 29  2018 stderr.txt
-rw-r--r-- 1 root root  61410896 Apr 27  2018 WebTorrentSetup-v0.20.0.exe
[root@VM_0_8_centos ~]# 
[root@VM_0_8_centos ~]# sudo rm /var/log/shiny-server/myShinyApp*
[root@VM_0_8_centos ~]# sudo rm -fr /srv/shiny-server/myShinyApp*
[root@VM_0_8_centos ~]# sudo rm -fr /srv/shiny-server/shinyParallel_appLink
[root@VM_0_8_centos ~]# cd ~
[root@VM_0_8_centos ~]# ll
total 720108
-rw-r--r-- 1 root root    302015 Oct 20  2017 3e9c099671820a30bf5d56e4a3814f64c831.pdf
-rw-r--r-- 1 root root  11237798 Sep  5  2018 apache-tomcat-8.5.34-windows-x64.zip
-rw-r--r-- 1 root root    188839 Jun 22 23:37 icudt61l.zip
-rw-r--r-- 1 root root      5444 Apr  7  2018 index.html
-rw-r--r-- 1 root root    238570 Dec 25 22:57 index.html.1
-rw-r--r-- 1 root root    149811 Dec 25 22:57 index.html?sku=Community
-rw-r--r-- 1 root root     26926 Oct  1  2018 jupyter_notebook_config.py
-rw-r--r-- 1 root root 170268287 Oct 21  2016 kie-server-distribution-6.5.0.Final.zip
-rw-r--r-- 1 root root    659802 Dec  5  2018 Lect1Station.pdf
-rw-r--r-- 1 root root  20105266 Jun 10  2018 LinuxProbe.pdf
-rw-r--r-- 1 root root   2928388 Oct 19  2018 master
-rw-r--r-- 1 root root      1022 Oct 20  2018 my.log
-rw-r--r-- 1 root root      6140 Nov 12  2015 mysql-community-release-el7-5.noarch.rpm
-rw------- 1 root root       462 Oct  1  2018 nohup.out
-rw-r--r-- 1 root root  83735016 Apr 26 19:16 R-3.6.0-win.exe
-rw-r--r-- 1 root root        59 Nov 29  2018 readme.txt
-rw-r--r-- 1 root root  89991619 Oct 30  2018 RStudio-1.1.463.exe
-rw-r--r-- 1 root root  18939524 Nov 26  2018 RStudio-1.2.1139.exe
-rw-r--r-- 1 root root     34436 Mar 30 19:04 RStudio-1.2.1335.exe
-rw-r--r-- 1 root root 133012196 Apr 13 20:42 RStudio-1.2.1335.exe.zip
-rw-r--r-- 1 root root  45678124 May 17  2018 rstudio-server-rhel-1.1.453-x86_64.rpm
-rw-r--r-- 1 root root  49141116 Apr  9 02:39 rstudio-server-rhel-1.2.1335-x86_64.rpm
drwxr-xr-x 3 root root      4096 Apr 11 22:49 sakila
-rw-r--r-- 1 root root       114 Apr 11 22:46 sakila-db.tar.gz
-rw-r--r-- 1 root root  48462832 Apr  7  2018 shiny-server-1.5.7.907-rh6-x86_64.rpm
drwxr-xr-x 2 root root      4096 Oct  1  2018 softwares
-rw-r--r-- 1 root root        52 Nov 29  2018 stderr.txt
-rw-r--r-- 1 root root  61410896 Apr 27  2018 WebTorrentSetup-v0.20.0.exe
[root@VM_0_8_centos ~]# cd ~;
[root@VM_0_8_centos ~]# mkdir myShinyApp;
[root@VM_0_8_centos ~]# echo "
>     library('shiny');
>     
>     # Create a Shiny app object
>     app <- shinyApp(
>       ui = fluidPage(
>         column(3, wellPanel(
>           numericInput('n', label='Is it prime?', value=7, min=1),
>           actionButton('check', 'Check!')
>         )
>       )),
>       server = function(input, output) {
>         # Check if n is prime.
>         # Not R optimized.
>         # No Fermat, Miller-Rabin, Solovay-Strassen, Frobenius, etc tests.
>         # Check if n is divisable up to n-1 !!
>         isPrime <- function(n) {
>           res <- TRUE;
>           i <- 2;
>           while (i < n) {
>             res <- res && n %% i != 0;
>             i <- i+1;
>           }
>           return(res);
>         }
>         observeEvent(input\$check, {
>           showModal(modalDialog(
>             ifelse(isPrime(isolate(input\$n)),
>                 'Yes it is!', 'Nope, not a prime.'),
>             footer=NULL,
>             easyClose=TRUE
>           ))
>         })
>       }
>     )
> " > myShinyApp/app.R;
[root@VM_0_8_centos ~]# sudo R

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> library("shinyParallel")
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
> # And install it
> shinyParallel::installShinyParallel("./myShinyApp",
+   max.sessions = 20,
+   users.per.session = 5
+ )
[1] "Copying shinyParallel server files."
[1] "Copying app files."
[2019-06-23 08:41:05] Exception: Pathname not found: myShinyApp (no such file in the current working directory; current directory is '/srv/shiny-server/shinyParallel_appLinks/myShinyApp')

  at #08. getReadablePathname.Arguments(static, ...)
          - getReadablePathname.Arguments() is in environment 'R.utils'

  at #07. getReadablePathname(static, ...)
          - getReadablePathname() is in environment 'R.utils'
          - originating from '<text>'

  at #06. Arguments$getReadablePathname(target, mustExist = TRUE)
          - Arguments$getReadablePathname() is local of the calling function

  at #05. createLink.default(paste0(appName, "_", i), appDir, overwrite = !F)
          - createLink.default() is in environment 'R.utils'

  at #04. createLink(paste0(appName, "_", i), appDir, overwrite = !F)
          - createLink() is in environment 'R.utils'

  at #03. FUN(X[[i]], ...)
          - FUN() is local of the calling function

  at #02. lapply(seq_len(max.sessions), function(i) {
              createLink(paste0(appName, "_", i), appDir, overwrite = !F)
          })
          - lapply() is in environment 'base'

  at #01. shinyParallel::installShinyParallel("./myShinyApp", max.sessions = 20, 
              users.per.session = 5)
          - shinyParallel::installShinyParallel() is in environment 'shinyParallel'

Error: Pathname not found: myShinyApp (no such file in the current working directory; current directory is '/srv/shiny-server/shinyParallel_appLinks/myShinyApp')
In addition: Warning message:
In normalizePath(target) :
  path[1]="./myShinyApp": No such file or directory
> sessioninfo::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       CentOS Linux 7 (Core)       
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.utf8                  
 ctype    en_US.utf8                  
 tz       Asia/Shanghai               
 date     2019-06-23                  

─ Packages ───────────────────────────────────────────────────────────────────
 package       * version date       lib
 assertthat      0.2.1   2019-03-21 [1]
 callr           3.2.0   2019-03-15 [1]
 cli             1.1.0   2019-03-19 [1]
 crayon          1.3.4   2017-09-16 [1]
 digest          0.6.19  2019-05-20 [1]
 htmltools       0.3.6   2017-04-28 [1]
 httpuv          1.5.1   2019-04-05 [1]
 later           0.8.0   2019-02-11 [1]
 magrittr        1.5     2014-11-22 [1]
 mime            0.7     2019-06-11 [1]
 processx        3.3.1   2019-05-08 [1]
 promises        1.0.1   2018-04-13 [1]
 ps              1.3.0   2018-12-21 [1]
 R.methodsS3     1.7.1   2016-02-16 [1]
 R.oo            1.22.0  2018-04-22 [1]
 R.utils         2.9.0   2019-06-13 [1]
 R6              2.4.0   2019-02-14 [1]
 Rcpp            1.0.1   2019-03-17 [1]
 sessioninfo     1.1.1   2018-11-05 [1]
 shiny           1.3.2   2019-04-22 [1]
 shinyParallel * 0.1.001 2019-06-21 [1]
 withr           2.1.2   2018-03-15 [1]
 xtable          1.8-4   2019-04-21 [1]
 source                                        
 CRAN (R 3.6.0)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.6.0)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.2)                                
 Github (jcrodriguez1989/shinyParallel@0d4e322)
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.2)                                

[1] /usr/lib64/R/library
[2] /usr/share/R/library
> q()
Save workspace image? [y/n/c]: n

## Now do it again

[root@VM_0_8_centos ~]# rm -rf myShinyApp/
[root@VM_0_8_centos ~]# sudo rm /var/log/shiny-server/myShinyApp*
rm: cannot remove ‘/var/log/shiny-server/myShinyApp*’: No such file or directory
[root@VM_0_8_centos ~]# sudo rm -fr /srv/shiny-server/myShinyApp*
[root@VM_0_8_centos ~]# sudo rm -fr /srv/shiny-server/shinyParallel_appLinks
[root@VM_0_8_centos ~]# cd ~;
[root@VM_0_8_centos ~]# mkdir myShinyApp;
[root@VM_0_8_centos ~]# echo "
>     library('shiny');
>     
>     # Create a Shiny app object
>     app <- shinyApp(
>       ui = fluidPage(
>         column(3, wellPanel(
>           numericInput('n', label='Is it prime?', value=7, min=1),
>           actionButton('check', 'Check!')
>         )
>       )),
>       server = function(input, output) {
>         # Check if n is prime.
>         # Not R optimized.
>         # No Fermat, Miller-Rabin, Solovay-Strassen, Frobenius, etc tests.
>         # Check if n is divisable up to n-1 !!
>         isPrime <- function(n) {
>           res <- TRUE;
>           i <- 2;
>           while (i < n) {
>             res <- res && n %% i != 0;
>             i <- i+1;
>           }
>           return(res);
>         }
>         observeEvent(input\$check, {
>           showModal(modalDialog(
>             ifelse(isPrime(isolate(input\$n)),
>                 'Yes it is!', 'Nope, not a prime.'),
>             footer=NULL,
>             easyClose=TRUE
>           ))
>         })
>       }
>     )
> " > myShinyApp/app.R;
[root@VM_0_8_centos ~]# sudo R

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> getwd()
[1] "/root"
> library("shinyParallel")
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
> # And install it
> shinyParallel::installShinyParallel("/root/myShinyApp",
+   max.sessions = 20,
+   users.per.session = 5
+ )
[1] "Copying shinyParallel server files."
[1] "Copying app files."
NULL
> sessioninfo::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       CentOS Linux 7 (Core)       
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.utf8                  
 ctype    en_US.utf8                  
 tz       Asia/Shanghai               
 date     2019-06-23                  

─ Packages ───────────────────────────────────────────────────────────────────
 package       * version date       lib
 assertthat      0.2.1   2019-03-21 [1]
 callr           3.2.0   2019-03-15 [1]
 cli             1.1.0   2019-03-19 [1]
 crayon          1.3.4   2017-09-16 [1]
 digest          0.6.19  2019-05-20 [1]
 htmltools       0.3.6   2017-04-28 [1]
 httpuv          1.5.1   2019-04-05 [1]
 later           0.8.0   2019-02-11 [1]
 magrittr        1.5     2014-11-22 [1]
 mime            0.7     2019-06-11 [1]
 processx        3.3.1   2019-05-08 [1]
 promises        1.0.1   2018-04-13 [1]
 ps              1.3.0   2018-12-21 [1]
 R.methodsS3     1.7.1   2016-02-16 [1]
 R.oo            1.22.0  2018-04-22 [1]
 R.utils         2.9.0   2019-06-13 [1]
 R6              2.4.0   2019-02-14 [1]
 Rcpp            1.0.1   2019-03-17 [1]
 sessioninfo     1.1.1   2018-11-05 [1]
 shiny           1.3.2   2019-04-22 [1]
 shinyParallel * 0.1.001 2019-06-21 [1]
 withr           2.1.2   2018-03-15 [1]
 xtable          1.8-4   2019-04-21 [1]
 source                                        
 CRAN (R 3.6.0)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.6.0)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.2)                                
 CRAN (R 3.5.1)                                
 CRAN (R 3.5.2)                                
 Github (jcrodriguez1989/shinyParallel@0d4e322)
 CRAN (R 3.5.0)                                
 CRAN (R 3.5.2)                                

[1] /usr/lib64/R/library
[2] /usr/share/R/library
> q()
Save workspace image? [y/n/c]: y
[root@VM_0_8_centos ~]# sudo ls -la /srv/shiny-server/
total 88
drwxr-xr-x  11 root root  4096 Jun 23 08:42 .
drwxr-xr-x.  3 root root  4096 Jul  7  2018 ..
drwxr-xr-x   2 root root  4096 Jun 21 23:44 app_parallel
drwxr-xr-x   4 root root  4096 Dec 23 16:56 css
-rw-r--r--   1 root root   335 Dec 23 16:56 favicon.png
drwxr-xr-x   4 root root  4096 Dec 23 16:56 fonts
drwxr-xr-x   2 root root  4096 Dec 23 16:56 images
-rw-r--r--   1 root root  8833 Dec 23 18:16 index.html
drwxr-xr-x   2 root root  4096 Dec 23 16:56 js
drwxr-xr-x   2 root root  4096 Jun 23 08:42 myShinyApp
drwxr-xr-x   2 root root  4096 Dec 23 17:00 personal_site
-rw-r--r--   1 root root  2586 Dec 23 18:02 .RData
-rw-------   1 root root    51 Dec 23 18:02 .Rhistory
lrwxrwxrwx   1 root root    37 Jul  7  2018 sample-apps -> /opt/shiny-server/samples/sample-apps
drwxr-xr-x   4 root root  4096 Jun 22 20:30 shiny-apps
drwxr-xr-x   3 root root  4096 Jun 23 08:42 shinyParallel_appLinks
-rw-r--r--   1 root root 19669 Dec 23 16:56 styles.html
[root@VM_0_8_centos ~]# sudo cat /var/log/shiny-server/myShinyApp*
su: ignore --preserve-environment, it's mutually exclusive to --login.
-bash: line 0: cd: /srv/shiny-server/shinyParallel_appLinks/myShinyApp/myShinyApp_1: Permission denied
```
Your can see that I still get the error.

**Comment by jcrodriguez1989** [comment]
You are having your workspace restored when you start R, that may cause an issue:
`[Previously saved workspace restored]`

When you open R, ensure that your working directory is the same in which you have 'myShinyApp' directory - in the example you should do `setwd("/root")` -
However, after your second execution, you are having the app correctly installed. Can you try entering the app?: [http://localhost:3838/myShinyApp/](http://localhost:3838/myShinyApp/)
And if it does not work, then check if we have any logs:
```r
sudo cat /var/log/shiny-server/myShinyApp*
cat /var/log/shiny-server/myShinyApp*
```

thanks

**Comment by Leo-Lee15** [comment]
I do enter the app. The url is http://139.199.106.172/myShinyApp/ . You can see the following error:
```
An error has occurred
The application failed to start.

The application exited during initialization.
```

And the log is the same.
```shell
[root@VM_0_8_centos ~]# cd  /var/log/shiny-server/
[root@VM_0_8_centos shiny-server]# ll
total 16
-rw-r----- 1 shiny shiny 174 Jun 23 08:43 myShinyApp_1-shiny-20190623-084300-43378.log
-rw-r----- 1 shiny shiny 174 Jun 23 09:38 myShinyApp_1-shiny-20190623-093817-40149.log
-rw-r----- 1 shiny shiny 174 Jun 24 09:29 myShinyApp_1-shiny-20190624-092915-37884.log
-rw-r----- 1 shiny shiny 108 Jun 24 09:29 myShinyApp-shiny-20190624-092856-39245.log
[root@VM_0_8_centos shiny-server]# rm -rf *
[root@VM_0_8_centos shiny-server]# ll
total 0

## I try enter the app in the browser
[root@VM_0_8_centos shiny-server]# ll
total 4
-rw-r----- 1 shiny shiny 175 Jun 24 09:30 myShinyApp_10-shiny-20190624-093051-45603.log
[root@VM_0_8_centos shiny-server]# cat myShinyApp_10-shiny-20190624-093051-45603.log
su: ignore --preserve-environment, it's mutually exclusive to --login.
-bash: line 0: cd: /srv/shiny-server/shinyParallel_appLinks/myShinyApp/myShinyApp_10: Permission denied
```
B.T.W, I use the remote server.

**Comment by jcrodriguez1989** [comment]
I get it, I think you are creating the app as root. You are having OS permission issues.
I mean, the README is meant to be run as a regular user, and do as root just the `installShinyParallel` step.

Do you have a regular user to create the app?

If not, you could also try:

```bash
su - shiny # login as shiny user
## create the app following the README
cd ~;
mkdir myShinyApp;
echo "
FILL WITH THE APP
" > myShinyApp/app.R;
exit;
```

And now install the app as root

```r
shinyParallel::installShinyParallel("/home/shiny/myShinyApp",
  max.sessions = 20,
  users.per.session = 5
)
```

**Comment by Leo-Lee15** [comment]
I've already tried other regular users, but all of them failed for the same permission reason. 
But when I login as shiny user, I succeed. 

I guess it will also be OK for regular users who belong to the shiny group.

Thank you very much for your generous help!

**Comment by jcrodriguez1989** [comment]
thank you for following my requests.
For sure I will try to improve this aspect of `shinyParallel` when I have some spare time.
